kafka {
  bootstrap-server = ${?KAFKA_BROKER_HOST}
  zookeeper-connect = ${?ZOOKEEPER_HOST_URL}
}

database {
  url = ${?DB_URL}      # Uses environment variable DB_URL if set
  user = ${?DB_USER}    # Uses environment variable DB_USER if set
  password = ${?DB_PASSWORD}  # Uses environment variable DB_PASSWORD if set
}