name: PDQA Microservices CI/CD
run-name: ${{ github.actor }} Running Pipeline
on:
    pull_request: 
      types:
        - closed
      branches:
        - feature/local-setup
    push:
      branches:
        - feature/local-setup

jobs: 
    build_develop:
        name: Build and Push Docker Image
        if: github.ref == 'refs/heads/feature/local-setup'
        environment: develop
        runs-on: ubuntu-latest
        outputs:
          output1: ${{ steps.step1.outputs.sha }}
        steps:
            - name: Checkout feature/local-setup
              uses: actions/checkout@v4

            - id: step1
              run: |
                echo "::set-output name=sha::$(echo $GITHUB_SHA)"
                echo $GITHUB_SHA > $GITHUB_WORKSPACE/_meta 

            -   name: Log in to GitHub Container Registry
                uses: docker/login-action@v2
                with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -   name: Build Container Image

                run: |
                    docker build -f Dockerfile \
                    -t ghcr.io/curiapp/curdev/pdqa-microservices:$(echo $GITHUB_SHA | head -c7) .

            -   name: Push image to GitHub Container Registry
                run: |
                      docker push ghcr.io/curiapp/curdev/pdqa-microservices:$(echo $GITHUB_SHA | head -c7)
              
    gitops_develop:
        name: Update GitOps Image Tag
        needs: build_develop
        if: github.ref == 'refs/heads/feature/local-setup'
        runs-on: ubuntu-latest
        steps:
        -   name: Clone GitOps repository
            uses: actions/checkout@v4
            with:
                repository: curiapp/dev-ops
                token: ${{ secrets.GITHUB_TOKEN }}
                ref: master

        -   name: Debug Permissions
            run: |
              echo "Checking GitHub Token Permissions..."
              curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                    -H "Accept: application/vnd.github.v3+json" \
                    https://api.github.com/repos/curiapp/dev-ops
        
        -   name: Kustomize CBI-develop
            if: github.repository == 'curiapp/curdev'
            run: |
                cd overlays/develop
                SHA=$(echo ${{needs.build_develop.outputs.output1}} | head -c7)
                kustomize edit set image ghcr.io/curiapp/curdev/pdqa-microservices:$SHA
                git config user.name github-actions[bot]
                git config user.email 41898282+github-actions[bot]@users.noreply.github.com
                git add .
                git commit -m "version-$SHA"
                git push 

    # develop-deploy:
    #     needs: gitops_develop
    #     runs-on: ubuntu-latest

